<?php
/**
 * Execute CSV import using mapping generated by the onboarding wizard.
 */

require_once '../config/app.php';
require_once '../config/security.php';
require_once '../includes/auth.php';
require_once '../includes/helpers.php';
require_once '../includes/Import/ImportManager.php';

$auth->requireAuth();
$auth->requireRole(ROLE_ADMIN);

header('Content-Type: application/json');

try {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        jsonResponse(['success' => false, 'message' => 'Method not allowed'], 405);
    }

    $rawBody = file_get_contents('php://input') ?: '';
    $payload = json_decode($rawBody, true);
    if (!is_array($payload)) {
        $payload = $_POST;
    }

    $csrfToken = $payload['csrf_token'] ?? null;
    if (!CSRF::validateToken($csrfToken)) {
        jsonResponse(['success' => false, 'message' => 'Invalid security token'], 403);
    }

    $dataset = trim((string)($payload['dataset'] ?? ''));
    $token = trim((string)($payload['token'] ?? ''));
    if ($dataset === '' || $token === '') {
        jsonResponse(['success' => false, 'message' => 'Dataset and token are required'], 422);
    }

    if (!preg_match('/^[a-f0-9]{32}$/', $token)) {
        jsonResponse(['success' => false, 'message' => 'Invalid token'], 422);
    }

    $mapping = $payload['mapping'] ?? [];
    if (!is_array($mapping)) {
        jsonResponse(['success' => false, 'message' => 'Invalid column mapping'], 422);
    }

    $options = [
        'update_existing' => !empty($payload['update_existing']),
        'skip_blank_updates' => !empty($payload['skip_blank_updates']),
    ];

    $tempDir = ROOT_PATH . '/storage/temp';
    $metaFile = $tempDir . '/import_' . $token . '.json';
    $csvFile = $tempDir . '/import_' . $token . '.csv';

    if (!file_exists($metaFile) || !file_exists($csvFile)) {
        jsonResponse(['success' => false, 'message' => 'Import session expired. Please upload the file again.'], 410);
    }

    $metadata = json_decode((string)file_get_contents($metaFile), true) ?: [];
    if (($metadata['dataset'] ?? '') !== $dataset) {
        jsonResponse(['success' => false, 'message' => 'Dataset mismatch. Please restart the import.'], 422);
    }

    $uploadedBy = $metadata['uploaded_by'] ?? null;
    if ($uploadedBy && isset($_SESSION['user_id']) && $uploadedBy !== $_SESSION['user_id']) {
        jsonResponse(['success' => false, 'message' => 'Import belongs to a different user session.'], 403);
    }

    $delimiter = $payload['delimiter'] ?? ($metadata['delimiter'] ?? ',');

    $importManager = new ImportManager();
    $summary = $importManager->importFromCsv($dataset, $csvFile, $delimiter, $mapping, $options);

    // Clean up temp files
    @unlink($csvFile);
    @unlink($metaFile);

    jsonResponse([
        'success' => true,
        'summary' => $summary,
    ]);
} catch (Throwable $e) {
    error_log('Import execution failed: ' . $e->getMessage());
    jsonResponse([
        'success' => false,
        'message' => $e->getMessage(),
    ], 500);
}


